### PR TITLE
Prompt for Java install if missing

### LINKED ISSUE #606: Installer doesn't warn about missing Java
As @lite1979 discovered testing #10, in 2.1.0, the Windows installer doesn't appear to warn when Java is missing, causing confusing to end-users.

### PR DESCRIPTION
**Pull request by tresf**
Closes #606

### CODE REVIEW

**Comment by klabarge** [comment]
On macOS, after clicking "OK", the AdoptOpenJDK installer page opened.

However, it opened the webpage in Safari, despite my default browser being Firefox

image

**Comment by klabarge** [comment]
Windows passed testing.

**Comment by tresf** [comment]
> However, it opened the webpage in Safari, despite my default browser being Firefox

Looks like it's using system defaults since `root` doesn't have one.  Fixed it to spawn as the current user per `93933aa`, can you try it again>

**Comment by tresf** [comment]
Hmm... testing failed, it still uses Safari.  Sorry, @klabarge we'll just have to live with this behavior for now.  There are some [ugly ways to detect the user](https://scriptingosx.com/2019/09/get-current-user-in-shell-scripts-on-macos/), but I'm not comfortable with adding that much logic for a small nuance like this.

**Comment by tresf** [comment]
Ok, I think I got macOS using the proper browser now using 0fb61c2.   @klabarge can you test again?  Also, can you double-check that Windows isn't launching the browser as Administrator?  That seems like it might open a can of worms.

**Comment by klabarge** [comment]
>  think I got macOS using the proper browser now using 0fb61c2

Works 👍 

> can you double-check that Windows isn't launching the browser as Administrator?

I don't think so, because it opened up in my existing browser session as a new tab

**Pull request merged**
