### PR TITLE
Fix forceRaw / altPrinting upgrade routine

### LINKED ISSUE #898: demo.qz.io uses "Force Raw" instead of "altPrinting", which doesn't work with 2.1.5 and lower
I noticed this on a client's machine a few days ago and confirmed today. 

The newer "Force Raw" flag is available on our test page https://demo.qz.io , but if the client machine is not using 2.2.0+, the printer will print the commands instead of parsing them.

### PR DESCRIPTION
**Pull request by tresf**
Closes #898

### CODE REVIEW

**Review by klabarge — APPROVED** [review]
I tested this change locally on macOS using QZ Tray 2.1.5 and it works

**Comment by tresf** [comment]
> I tested this change locally on macOS using QZ Tray 2.1.5 and it works

Awesome.  We also need to regression test this against the known-working QZ Tray 2.1.3 as well as make sure it causes no regressions with newer versions such as QZ Tray 2.2.1.

**Comment by tresf** [comment]
> Awesome. We also need to regression test this against the known-working QZ Tray 2.1.3 as well as make sure it causes no regressions with newer versions such as QZ Tray 2.2.1.

Clarification: The new 2.2.1 version should be confirmed via the logs to ensure that `forceRaw` comes across still, not `altPrintint`.

**Comment by klabarge** [comment]
I've confirmed that 2.2.1 uses `forceRaw` 👍

**Pull request merged**
