### PR TITLE
Firefox preemptive certificate install

### LINKED ISSUE #697: Preemptive Firefox cert installation
Placeholder to setup Firefox if it's been installed or modified AFTER QZ Tray is installed (requires elevation)

### PR DESCRIPTION
**Pull request by tresf**
Adds a preemptive system-wide policy (Group Policy area on Windows, `/Library/Preferences` on macOS) for Firefox to trust QZ Tray certificates.

Closes #697

### CODE REVIEW

**Comment by tresf** [comment]
@bberenz can you please do a code review on this?

@klabarge can you please test this on Windows and MacOS?

**Comment by klabarge** [comment]
@tresf should I see this registry value immediately after install?

```cmd
C:\> reg delete HKCU\Software\Policies\Mozilla /f
ERROR: The system was unable to find the specified registry key or value.
```

**Comment by tresf** [comment]
No, it's a retroactive setting, it only gets created at run-time (not install-time) if Firefox is detected AND the policy is missing (e.g. Firefox was installed after QZ Tray)

**Comment by klabarge** [comment]
> it only gets created at run-time (not install-time) if Firefox is detected AND the standard system-wide policy is missing (e.g. Firefox was installed after QZ Tray)

Ahhh thanks for the clarification.


On my machine access is denied updating the registry. Even though it fails, it continues, prompting to restart Firefox. It does this endlessly.

image

```
[WARN] 2020-08-07 11:10:47,482 @ qz.installer.certificate.firefox.FirefoxCertificateInstaller:?
	SSL support for Mozilla Firefox (C:\Program Files\Mozilla Firefox) is missing. We'll attempt to install it...
[ERROR] 2020-08-07 11:10:47,483 @ qz.utils.WindowsUtilities:?
	Could not write registry value HKEY_CURRENT_USER\Software\Policies\Mozilla\Firefox\Certificates\ImportEnterpriseRoots
com.sun.jna.platform.win32.Win32Exception: Access is denied.
	at com.sun.jna.platform.win32.Advapi32Util.registryCreateKey(Advapi32Util.java:1073)
	at qz.utils.WindowsUtilities.addRegValue(Unknown Source)
	at qz.installer.certificate.firefox.FirefoxCertificateInstaller.installAlternatePolicy(Unknown Source)
	at qz.installer.certificate.firefox.FirefoxCertificateInstaller.fixMissingPolicies(Unknown Source)
	at qz.common.TrayManager.lambda$new$0(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:834)
[DEBUG] 2020-08-07 11:10:47,484 @ qz.utils.ShellUtilities:?
	Executing: [wmic.exe, process, where, (Name='firefox.exe'), get, processid]
[DEBUG] 2020-08-07 11:10:47,981 @ qz.utils.ShellUtilities:?
	Executing: [wmic.exe, process, where, ProcessId=41788, get, ExecutablePath]
[DEBUG] 2020-08-07 11:10:48,482 @ qz.utils.ShellUtilities:?
	Executing: [wmic.exe, process, where, ProcessId=2492, get, ExecutablePath]
[DEBUG] 2020-08-07 11:10:48,984 @ qz.utils.ShellUtilities:?
	Executing: [wmic.exe, process, where, ProcessId=38496, get, ExecutablePath]
[DEBUG] 2020-08-07 11:10:49,491 @ qz.utils.ShellUtilities:?
	Executing: [wmic.exe, process, where, ProcessId=56192, get, ExecutablePath]
[DEBUG] 2020-08-07 11:10:49,985 @ qz.utils.ShellUtilities:?
	Executing: [wmic.exe, process, where, ProcessId=47720, get, ExecutablePath]
[DEBUG] 2020-08-07 11:10:50,490 @ qz.utils.ShellUtilities:?
	Executing: [wmic.exe, process, where, ProcessId=52696, get, ExecutablePath]
[DEBUG] 2020-08-07 11:10:50,980 @ qz.utils.ShellUtilities:?
	Executing: [net, session]
[DEBUG] 2020-08-07 11:10:51,024 @ qz.utils.ShellUtilities:?
	Executing: [C:\Program Files\Mozilla Firefox\firefox.exe, -private, about:restartrequired]
```

**Comment by klabarge** [comment]
This works well on macOS. If I `defaults delete org.mozilla.firefox`, the cert is reinstalled and Firefox is prompted to restart.

**Comment by tresf** [comment]
>  Even though it fails, it continues, prompting to restart Firefox. It does this endlessly

Whoops.  Ok, well now that's patched via 7d74f61.


> On my machine access is denied updating the registry.

I had that too.  I was hoping it was an edge-case, but apparently [it's not](https://serverfault.com/a/369546/344981).  Ok, I'll have to rethink my approach.  For now, I think I'll just install the system-wide policy and get rid of the listener.  This means we'll have to redo the testing once the new technique is completed.   Thanks kindly for the testing.

**Comment by tresf** [comment]
@klabarge sorry for the delay, this is ready for re-review.  The title and description has changed as has the strategy.

Cleanup between testing is a very manual process.

macOS:
```bash
sudo defaults delete /Library/Preferences/org.mozilla.firefox
sudo rm -rf /Applications/Firefox.app/Contents/Resources/distribution/
# repeat for Waterfox if needed
# Seamonkey or Pale Moon will require deletion of /Contents/Resources/qz-tray.cfg and /Contents/Resources/defaults/pref/qz-tray.js deleted
```

Windows:
```cmd
REM As Administrator
reg delete HKLM\Software\Policies\Mozilla /f
del /s "%programfiles%\Mozilla Firefox\distribution\"
REM repeat for Waterfox if needed
REM Seamonkey or Pale Moon will require deletion of \qz-tray.cfg and \defaults\pref\qz-tray.js 
```

Linux:
```bash
# Should be identical behavior as before, enterprise policies aren't supported
```

**Comment by tresf** [comment]
Quoting @klabarge (Slack):

> WIndows seems to work great. On macOS, if FIrefox is installed after QZ Tray, HTTPS doesn’t work

... so there's some work to be done before this is merged.  I may need to revert macOS to use the previous technique -- the one that ran with user permissions.

**Comment by tresf** [comment]
macOS was just a typo, patched via 91b8db7. @klabarge can you re-test?

**Comment by klabarge** [comment]
I re-tested macOS, Windows and Linux after the last commit and it looks good.

||macOS| Windows| Linux|
|-|-|-|-| 
|Firefox after| ✅ | ✅  | N/A|
|Firefox before | ✅ | ✅ | ✅ |

**Pull request merged**
