### PR TITLE
JavaFX version info

### LINKED ISSUE #421: Show JavaFX version information
Similar to the library version information offered in dde7798, placeholder to add JavaFX library version information.

Note, JavaFX may be derived from the following locations:
* Bundled (JDK11) (#407, #419)
* OracleJDK (Bundled with Java 7, 8)
* OpenJFX (Available from `apt-get`, `dnf`, etc)

### PR DESCRIPTION
**Pull request by Vzor-**
closes #421 
also added jre version and vendor.

### CODE REVIEW

**Comment by klabarge** [comment]
I've uploaded installers for testing here: https://github.com/klabarge/tray/releases/tag/v2.0.9-javafx

I've tested on macOS, can test other OS's later.

**macOS**

image

**Comment by Vzor-** [comment]
@klabarge could you also include the jre and jre (vendor) fields?

**Comment by tresf** [comment]
@Vzor- can you please add `System.getProperty("java.vendor")` to https://github.com/qzind/tray/blob/2.0/src/qz/ws/PrintSocketServer.java#L88 as well for consistency?

**Comment by klabarge** [comment]
>@klabarge could you also include the jre and jre (vendor) fields?

I've updated the test results for all platforms. I only tested the different vendors (Oracle, OpenJDK, and AdoptOpenJDK) on Linux.

**Pull request merged**
