### PR TITLE
Log4j update

### PR DESCRIPTION
**Pull request by bberenz**
**Edit:** Related #893 #895

### CODE REVIEW

**Comment by tresf** [comment]
@lite1979 and myself tested this on Ubuntu and we received the following error:

```
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
Exception in thread "main" java.lang.ClassCastException: class org.apache.logging.log4j.simple.SimpleLogger cannot be cast to class org.apache.logging.log4j.core.Logger (org.apache.logging.log4j.simple.SimpleLogger and org.apache.logging.log4j.core.Logger are in unnamed module of loader 'app')
	at qz.utils.LoggerUtilities.getRootLogger(Unknown Source)
	at qz.App.setupFileLogging(Unknown Source)
	at qz.App.main(Unknown Source)
```

@bberenz any idea why?

**Comment by bberenz** [comment]
Seems as though it can't find the log4j-core-2.16.0 jar. No idea why, is there something we need to change so ubuntu sees the updated /lib folder?

**Comment by tresf** [comment]
Well, for some reason, c435ab3, specifically `META-INF/versions` causes this to happen at runtime.

```
WARNING: Unknown module: java.desktop specified to --add-exports
WARNING: Unknown module: java.desktop specified to --add-exports
WARNING: Unknown module: java.desktop specified to --add-opens
WARNING: Unknown module: java.desktop specified to --add-opens
Exception in thread "main" java.lang.NoClassDefFoundError: javax/naming/Context
	at org.apache.logging.log4j.core.lookup.Interpolator.<init>(Interpolator.java:112)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.<init>(AbstractConfiguration.java:131)
	at org.apache.logging.log4j.core.config.NullConfiguration.<init>(NullConfiguration.java:32)
	at org.apache.logging.log4j.core.LoggerContext.<clinit>(LoggerContext.java:85)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:254)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:218)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:136)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:123)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:117)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:150)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:599)
	at qz.App.<clinit>(Unknown Source)
Caused by: java.lang.ClassNotFoundException: javax.naming.Context
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more
```

**Comment by tresf** [comment]
So, I believe the `META-INF/versions/9/module-info.class` file that ships with Log4J was clobbering our own, which was newly created with the newly added `Multi-Release` flag.

**Comment by lite1979** [comment]
Tested on Metal with Windows 10, Ubuntu 20.04, and MacOS Big Sure (Intel). Logs look good on all three!

**Pull request merged**
