### PR TITLE
add support.md file

### PR DESCRIPTION
**Pull request by klabarge**

### CODE REVIEW

**Comment by klabarge** [comment]
@tresf, is this okay to merge?

**Comment by tresf** [comment]
@klabarge I just cloned this and it's not working on my fork.  I'd like to preview it before merging it.

https://github.com/tresf/tray/blob/2.0/.github/SUPPORT.md

**Comment by tresf** [comment]
@klabarge I tested this on a [brand new repo](https://github.com/tresf/testtray/issues/new) too, the feature seems to be broken.  Perhaps support can help.

**Comment by tresf** [comment]
Apparently this won't show for project maintainers.  Validated on eachother's forks.  Merged.

**Pull request merged**
