### PR TITLE
Additional backwards conversion for newer data formats

### PR DESCRIPTION
**Pull request by bberenz**
for #665

### CODE REVIEW

**Comment by klabarge** [comment]
>but I'm pretty sure the backticks break IE11 support, which we haven't officially done yet.
Confirmed that this does break IE11.

**Comment by tresf** [comment]
@klabarge I did a quick edit through the web interface if you don't mind trying it again.

**Comment by tresf** [comment]
@klabarge bump. :)

**Comment by klabarge** [comment]
This does work.

image

However, when using the `sample.html`, the code never makes it to the `catch`  therefore does not show an error to the user. Can we display an error message to the user?

```js
    function sendHidData() {
        qz.hid.sendData({
                            vendorId: $("#hidVendor").val(),
                            productId: $("#hidProduct").val(),
                            usagePage: $("#hidUsagePage").val(),
                            serial: $("#hidSerial").val(),
                            data: {data:"dd", type: "HEX"},
                            endpoint: $("#hidReport").val()
                        })
            .catch(displayError);
    }
```

**Comment by tresf** [comment]
Good idea, prob shoulda been there all along.  Do you mind adding the commit?

**Comment by klabarge** [comment]
@tresf I am struggling to catch this error properly.

If I switch the line to `Promise.reject`, the promise seems to hit the catch block.
   * Notice the additional  `no output reports` error in the console (which is because the HID device I am testing against doesn't support sending data to it).

However, the `Data format` error still shows as uncaught.

```js
Promise.reject("Data format is not supported with connected QZ Tray version " + _qz.websocket.connection.version);
```

image

**Comment by tresf** [comment]
@klabarge yeah, I appears @bberenz is throwing this in the middle of a promise, so it's unhandled.

@bberenz is this behavior desired?  As-is, it can't be caught.

**Comment by bberenz** [comment]
You need to change it to `return Promise.reject(new Error("..."));` for this to work how you are expecting.

**Comment by tresf** [comment]
Assuming we wrap it in our `_qz.tools.proimse` to make it Promise agnostic (RSVP, Q, BlueBird, etc), would this work?

```js
   tools:
        // ... 
            /** Stub for rejecting with an Error from withing a promise */
            reject: function(error) {
                return _qz.tools.promise(new function(resolve, reject)) {
                    reject(error);
                }
            },
```


Usage:
```js
return _qz.tools.reject(new Error("..."));

```

**Comment by tresf** [comment]
Quoting @bberenz 

> 👍 

😅 OK, @klabarge great catch.... Can you test e7e714 and see if it remedy's it?  It adds a new `_qz.tools.reject(new Error(...))` syntax that allows just this.

**Comment by klabarge** [comment]
I think there was a syntax error which I fixed in [85540f2](https://github.com/qzind/tray/pull/951/commits/85540f248a0ff17871217eeec684b5f39fdeb325)

However, it's still showing as an `Uncaught (in promise) Error` in the browser console.

**Comment by tresf** [comment]
Thanks for fixing the typo.  I think I forgot a `return`.  Can you test with f3efde9?

**Comment by klabarge** [comment]
Yes that did the trick!

**Review by tresf — APPROVED** [review]

**Pull request merged**
