### PR TITLE
Build Constants.java from ant properties, get project version from git

### PR DESCRIPTION
**Pull request by lukas-w**
Moved Constants.java to Constants.java.template, which is now being processed by ant's `expandproperties` filter. The project version is read using `git describe` (formatted as e.g. `2.0.1-14` when building from a branch 14 commits ahead of the tag v2.0.1). We may still want to have the current release hard-coded somewhere as a fallback when git is not available.

### CODE REVIEW

**Comment by tresf** [comment]
>  We may still want to have the current release hard-coded somewhere as a fallback when git is not available.

This definitely is a concern of mine because we run from IDE (IntelliJ) quite often, which won't run unless the project has first been configured by ant.

**Comment by Lukas-W** [comment]
Added a default version to `project.properties` and modified `build.xml` to not fail when git's unavailable on the system

**Comment by tresf** [comment]
> Added a default version to project.properties and modified build.xml to not fail when git's unavailable on the system

I think this will still fail when run from IDE tho.

**Comment by Lukas-W** [comment]
I guess I'm out of my depth here then. Doesn't IntelliJ use ant's build.xml?

**Comment by tresf** [comment]
> Doesn't IntelliJ use ant's build.xml?

No, it uses some [custom logic](http://stackoverflow.com/a/25066395/3196753).  Note, IntelliJ community edition works great on Linux if you have time to see how it works.

https://qz.io/wiki/Compiling#intellij

**Comment by tresf** [comment]
We still need a way of auto-incrementing the builds but our White-Label portal has this ability already and making IntelliJ and ant both happy is going to take some reconsideration.  I'm closing this PR, but we'll reference it for the future (e.g. if we ever start releasing nightly builds to the general public).

**Pull request closed without merging**
