### PR TITLE
Whitelist qz protocol handler for Google Chrome

### PR DESCRIPTION
**Pull request by tresf**
Per #526, adds `qz:launch` support to Chrome, Chromium by whitelisting the `qz:` URL on Windows, Mac and Linux.

### CODE REVIEW

**Comment by klabarge** [comment]
This works on macOS and Windows. I found that Chrome does need to be restarted for it to take effect.

This doesn't seem to work on Ubuntu 18.0.4 64-bit

- Chrome Version 80.0.3987.106 (Official Build) (64-bit)
- I installed Chrome using `sudo dpkg -i google-chrome-stable_current_amd64.deb`

I checked both of these directories `/etc/chromium/policies/managed`, `/etc/opt/chrome/policies/managed` and the `qz-tray.json` file does exist

image

**Comment by tresf** [comment]
They should exist, perhaps with the wrong permissions?

I'm using `PosixFilePermissions.fromString("rwxr-xr-x")` but they don't seem to be taking on a fresh machine.  I'll see what's going on...

https://github.com/qzind/tray/blob/f945c255da1ce2d829d330643ba79a19a423088c/src/qz/installer/LinuxInstaller.java#L110-L117

**Comment by tresf** [comment]
Ugh... It's the `umask`.... https://stackoverflow.com/a/44923969/3196753

**Comment by tresf** [comment]
@klabarge ok, I've patched the permissions per 28dd5bc.  Linux is ready for testing.

**Comment by klabarge** [comment]
Tested on Ubuntu and the patch works 👍

**Pull request merged**
