### PR TITLE
Lazy load printer resolutions (2.1)

### LINKED ISSUE #932: Lazy fetch print density
The NativePrinter.java looks for PrinterResolution when populating the printer listing, causing the search to run very slowly.

If we can grab this lazily, printer searching will be much faster.

### PR DESCRIPTION
**Pull request by bberenz**
Fixes #932

### CODE REVIEW

**Review by tresf — APPROVED** [review]

**Comment by klabarge** [comment]
I tested this on macOS, Ubuntu, and Windows and in all scenarios printers.find was faster with this patch. Even with testing against 6-7 printers, the operation completed faster.

Is this IDLE task necessary now, since it completes immediately?

### macOS stable
```
[DEBUG] 2022-03-09 10:46:01,928 @ qz.common.TrayManager:?
	IDLE: Performing first run of find printers
[DEBUG] 2022-03-09 10:46:02,389 @ qz.utils.ShellUtilities:?
	Executing: [lpstat, -l, -p]
[DEBUG] 2022-03-09 10:46:02,694 @ qz.printer.PrintServiceMatcher:?
	Found 7 printers
[DEBUG] 2022-03-09 10:46:02,695 @ qz.utils.ShellUtilities:?
	Executing: [lpoptions, -p, _10_10_0_54]
[DEBUG] 2022-03-09 10:46:02,777 @ qz.utils.ShellUtilities:?
	Executing: [lpoptions, -p, HP_LaserJet_M603]
[DEBUG] 2022-03-09 10:46:02,856 @ qz.utils.ShellUtilities:?
	Executing: [lpoptions, -p, _10_10_1_29]
[DEBUG] 2022-03-09 10:46:02,935 @ qz.utils.ShellUtilities:?
	Executing: [lpoptions, -p, PDFwriter]
[DEBUG] 2022-03-09 10:46:03,010 @ qz.utils.ShellUtilities:?
	Executing: [lpoptions, -p, Zebra_raw]
[DEBUG] 2022-03-09 10:46:03,086 @ qz.utils.ShellUtilities:?
	Executing: [lpoptions, -p, testp]
[DEBUG] 2022-03-09 10:46:03,162 @ qz.utils.ShellUtilities:?
	Executing: [lpoptions, -p, EPSON_ET_2720_Series]
```

### macOS lazy load
```
[DEBUG] 2022-03-09T10:51:59,989 @ qz.common.TrayManager:-1
	IDLE: Performing first run of find printers
[DEBUG] 2022-03-09T10:52:00,412 @ qz.utils.ShellUtilities:-1
	Executing: [lpstat, -l, -p]
[DEBUG] 2022-03-09T10:52:00,703 @ qz.utils.ShellUtilities:-1
	Executing: [lpoptions, -p, _10_10_0_54]
[DEBUG] 2022-03-09T10:52:00,791 @ qz.utils.ShellUtilities:-1
	Executing: [lpoptions, -p, HP_LaserJet_M603]
[DEBUG] 2022-03-09T10:52:00,867 @ qz.utils.ShellUtilities:-1
	Executing: [lpoptions, -p, _10_10_1_29]
[DEBUG] 2022-03-09T10:52:00,946 @ qz.utils.ShellUtilities:-1
	Executing: [lpoptions, -p, PDFwriter]
[DEBUG] 2022-03-09T10:52:01,020 @ qz.utils.ShellUtilities:-1
	Executing: [lpoptions, -p, Zebra_raw]
[DEBUG] 2022-03-09T10:52:01,097 @ qz.utils.ShellUtilities:-1
	Executing: [lpoptions, -p, testp]
[DEBUG] 2022-03-09T10:52:01,173 @ qz.utils.ShellUtilities:-1
	Executing: [lpoptions, -p, EPSON_ET_2720_Series]
[DEBUG] 2022-03-09T10:52:01,247 @ qz.printer.PrintServiceMatcher:-1
	Found 7 printers
```


### Windows stable
```[DEBUG] 2022-03-09 11:19:19,090 @ qz.common.TrayManager:?
        IDLE: Performing first run of find printers
[INFO] 2022-03-09 11:20:07,203 @ qz.installer.certificate.CertificateManager:?
        SSL certificate is still valid for 657 more days: 2023-12-26T23:53Z.  We'll make a new one automatically when needed.
[DEBUG] 2022-03-09 11:21:01,828 @ qz.printer.PrintServiceMatcher:?
        Found 1211 printers
```

### Windows lazy load
```[DEBUG] 2022-03-09T11:34:34,616 @ qz.common.TrayManager:-1
        IDLE: Performing first run of find printers
[DEBUG] 2022-03-09T11:34:35,006 @ qz.printer.PrintServiceMatcher:-1
        Found 1211 printers
```

### Linux stable
```
[DEBUG] 2022-03-09T09:05:58,846 @ qz.common.TrayManager:-1
	IDLE: Performing first run of find printers
[DEBUG] 2022-03-09T09:05:59,148 @ qz.utils.ShellUtilities:-1
	Executing: [lpstat, -l, -p]
[DEBUG] 2022-03-09T09:05:59,550 @ qz.printer.PrintServiceMatcher:-1
	Found 6 printers
[DEBUG] 2022-03-09T09:05:59,551 @ qz.utils.ShellUtilities:-1
	Executing: [lpoptions, -p, PDF]
[ERROR] 2022-03-09T09:05:59,830 @ qz.printer.info.CupsPrinterMap:-1
	Something went wrong while reading /etc/cups/ppd/PDF.ppd
[DEBUG] 2022-03-09T09:05:59,831 @ qz.utils.ShellUtilities:-1
	Executing: [lpoptions, -p, Zebra_LP2844]
[ERROR] 2022-03-09T09:06:00,104 @ qz.printer.info.CupsPrinterMap:-1
	Something went wrong while reading /etc/cups/ppd/Zebra_LP2844.ppd
[DEBUG] 2022-03-09T09:06:00,105 @ qz.utils.ShellUtilities:-1
	Executing: [lpoptions, -p, EPSON_WF_3730_Series]
[DEBUG] 2022-03-09T09:06:00,225 @ qz.utils.ShellUtilities:-1
	Executing: [lpoptions, -p, EPSON_WF-3730_Series]
[ERROR] 2022-03-09T09:06:00,350 @ qz.printer.info.CupsPrinterMap:-1
	Something went wrong while reading /etc/cups/ppd/EPSON_WF-3730_Series.ppd
[DEBUG] 2022-03-09T09:06:00,350 @ qz.utils.ShellUtilities:-1
	Executing: [lpoptions, -p, EPSON_TM-T88VI]
[ERROR] 2022-03-09T09:06:00,473 @ qz.printer.info.CupsPrinterMap:-1
	Something went wrong while reading /etc/cups/ppd/EPSON_TM-T88VI.ppd
[DEBUG] 2022-03-09T09:06:00,473 @ qz.utils.ShellUtilities:-1
	Executing: [lpoptions, -p, Epson_TM88VI_Raw]
```

### Linux lazy
```
[DEBUG] 2022-03-09T09:01:17,112 @ qz.common.TrayManager:-1
	IDLE: Performing first run of find printers
[DEBUG] 2022-03-09T09:01:17,421 @ qz.utils.ShellUtilities:-1
	Executing: [lpstat, -l, -p]
[DEBUG] 2022-03-09T09:01:17,703 @ qz.utils.ShellUtilities:-1
	Executing: [lpoptions, -p, PDF]
[ERROR] 2022-03-09T09:01:17,824 @ qz.printer.info.CupsPrinterMap:-1
	Something went wrong while reading /etc/cups/ppd/PDF.ppd
[DEBUG] 2022-03-09T09:01:17,825 @ qz.utils.ShellUtilities:-1
	Executing: [lpoptions, -p, Zebra_LP2844]
[ERROR] 2022-03-09T09:01:18,112 @ qz.printer.info.CupsPrinterMap:-1
	Something went wrong while reading /etc/cups/ppd/Zebra_LP2844.ppd
[DEBUG] 2022-03-09T09:01:18,113 @ qz.utils.ShellUtilities:-1
	Executing: [lpoptions, -p, EPSON_WF_3730_Series]
[DEBUG] 2022-03-09T09:01:18,233 @ qz.utils.ShellUtilities:-1
	Executing: [lpoptions, -p, EPSON_WF-3730_Series]
[ERROR] 2022-03-09T09:01:18,356 @ qz.printer.info.CupsPrinterMap:-1
	Something went wrong while reading /etc/cups/ppd/EPSON_WF-3730_Series.ppd
[DEBUG] 2022-03-09T09:01:18,356 @ qz.utils.ShellUtilities:-1
	Executing: [lpoptions, -p, EPSON_TM-T88VI]
[ERROR] 2022-03-09T09:01:18,451 @ qz.printer.info.CupsPrinterMap:-1
	Something went wrong while reading /etc/cups/ppd/EPSON_TM-T88VI.ppd
[DEBUG] 2022-03-09T09:01:18,453 @ qz.utils.ShellUtilities:-1
	Executing: [lpoptions, -p, Epson_TM88VI_Raw]
[DEBUG] 2022-03-09T09:01:18,727 @ qz.printer.PrintServiceMatcher:-1
	Found 6 printers
```

**Comment by tresf** [comment]
Fantastic question.  We took density out to prevent the hard crashes.   Perhaps we try to find a middle ground with the Printer Details.  @bberenz we found that density was crashing FX but only if FX was loaded afterwards.

Perhaps we move FX up in the queue and cache density as a background task.

**Comment by tresf** [comment]
> Is this IDLE task necessary now, since it completes immediately?

Addressed in dd02184 by bring back the longer running task, but placing it after JavaFX.

@bberenz review requested.
@klabarge testing requested.

**Comment by bberenz** [comment]
Changes you made look good, @tresf

**Comment by tresf** [comment]
Thanks @bberenz.  @klabarge I'm going to merge, so this will need to be tested on 2.1.

**Comment by tresf** [comment]
Cherry-picked dd02184 to master via 58c140b.

**Comment by klabarge** [comment]
This does work fine, however I have an observation...

I noticed it takes about 1 minute after QZ Tray starts up for the JavaFX task to begin. After the JavaFX task completes, it takes another minute for the printer task to begin.

Are these intentional buffers?

```
[TRACE] 2022-03-22T21:39:41,414 @ qz.common.AboutInfo:-1
        Found latest version of QZ Tray online: 2.2.1
[INFO] 2022-03-22T21:40:38,493 @ qz.installer.certificate.CertificateManager:-1
        SSL certificate is still valid for 824 more days: 2024-06-24T01:21Z.  We'll make a new one automatically when needed.
[DEBUG] 2022-03-22T21:40:40,313 @ qz.common.TrayManager:-1
        IDLE: Starting up JFX for HTML printing

[TRACE] 2022-03-22T21:40:41,555 @ qz.printer.action.WebApp:-1
        JFX initialized successfully
[DEBUG] 2022-03-22T21:41:40,298 @ qz.common.TrayManager:-1
        IDLE: Performing first run of find printers
```

**Comment by tresf** [comment]
> Are these intentional buffers?

Thanks, yes, they were intentional.  The original delays were arbitrary but during support session were a bit too fast to startup.  These new delays give the app some time to start up and be used by the browser before they run.

**Comment by klabarge** [comment]
Okay, thanks Tres. This is good, then. I tested this on the 2.2 branch including:

* Using HTML printing before the JavaFX IDLE task
* Using findPrinters before the IDLE task
* Using the QZ Tray menu while printer caching is happening

**Pull request merged**
