### PR TITLE
Log4j update (2.1)

### PR DESCRIPTION
**Pull request by bberenz**
**Edit:** Related #893 #895

### CODE REVIEW

**Comment by tresf** [comment]
@bberenz for some reason the Log Dialog as well as the log files (e.g. those normally found in `%APPDATA%\qz`) are completely empty.  Any clue as to why?

**Comment by bberenz** [comment]
They appear to be working fine on my end. Are you getting any errors in the console?

**Comment by tresf** [comment]
> They appear to be working fine on my end. Are you getting any errors in the console?

Hadn't tried interactively (and the ones we'd normally use are missing, so a bit of a catch-22)

**Comment by bberenz** [comment]
Oh I suppose I am running from intellij, I can try running from installer when I have some time available later today.

**Comment by tresf** [comment]
> Oh I suppose I am running from intellij, I can try running from installer when I have some time available later today.

Oh that's even stranger.  I wonder why it would it work in IDE but not installed.... that's bazaar.  I can confirm that the Log Dialog and files are working just fine from IDE.   Does this suggest that the config file isn't being read for some reason?

**Comment by tresf** [comment]
> Oh I suppose I am running from intellij, I can try running from installer when I have some time available later today.

So the interactive console is working when I start QZ Tray manually, but the Log Dialog is still empty.  No glaring issues in the interactive logs suggesting why.

So, I'm still perplexed by the difference in behavior between IDE and installed version for the 2.1 branch.

**Comment by lite1979** [comment]
Tested on Metal with Windows 10, Ubuntu 20.04, and MacOS Big Sur (Intel). Logs look good!

**Pull request merged**
