### PR TITLE
I18nsupport

### PR DESCRIPTION
**Pull request by johann-sonntagbauer**
This pull request combines #290 and the following changes

* gettext extraction Ant Task
* change language UI
* german translations

### CODE REVIEW

**Comment by tresf** [comment]
@johann-sonntagbauer thanks! 

Some notes:

- There are a lot of whitespace changes (especially `build.xml`, but a lot in `.java` files too) that should not be in this PR that are not needed for merge and should be removed.
- Am I right in assuming `extractGettextTask` is compiled from source and then used later in ant? This seems like overkill and adds seems to add a redundant `PESignerTask` in `build.xml`.  If we can figure out a way to avoid the redundancy it would be appreciated.

**Comment by johann-sonntagbauer** [comment]
@tresf 
* sorry for the formatting (whitespace) issues. I will try to clean them up.
* yes you are right, it is compiled and used. Maybe shipping a prebuilt jar would also do the trick.

**Comment by tresf** [comment]
I've removed the `build.xml` formatting changes for readability.  We can put them back in but it makes the PR easier to review for now.

So I've gone through some `ant` language utilities and there appears to be a project called `jgettext`.  Unfortunately it seems to be designed solely for the `.po` files that @liushuyu originally wanted to use when he started his PR.

So now I'm in a bit of a dilemma.  If the various tools of the internet want `.po` files and @liushuyu's initial instinct was to use `.po` files, perhaps we just bundle a few ANT utilities and embrace the format.

I've granted @liushuyu push access to the repo so that he can close his PR and start working from this one.  I'm going to need some advice here.  I like the simplicity of the `.properties` files but I'd rather not make in interim build step just for an internal utility.

Alternatively, we could add an entry point to `main(...)` inside `PrintSocketServer`, but that seems overkill.

Thoughts?

**Comment by tresf** [comment]
@johann-sonntagbauer some cosmetic notes... 

* The language dialog icons should look like this:
   screen shot 2018-04-07 at 3 22 35 pm<br>You can safely extend `ConfirmDialog` class if you'd like, which will make translation easier.<br>
Currently the icons are backwards, "Close" actually cancels. :)
   screen shot 2018-04-07 at 3 29 18 pm

* The language selector should be a dropdown and -- if possible -- it would be nice to have some sample text available in preview form.
* The language selector should have each language in its native language.  [Example here.](https://user-images.githubusercontent.com/6345473/38459521-9b1ad5a0-3a78-11e8-97df-727a2323728e.png).  I assume the current framework makes this possible.  If not, we might need to figure out how possible this is.

**Comment by tresf** [comment]
Some bugs... 
* Currently when "Save" is closed on Mac, the software closes and does not reopen.

**Comment by johann-sonntagbauer** [comment]
@tresf thanks for the input, it is quite late today. I will try to address them tomorrow.

**Comment by johann-sonntagbauer** [comment]
* translation file format. I don't have a strong opinion on that one. Because of the small project size any implementation will do. There is great tooling support to edit *.properties files in IntelliJ. *.po is a more common file type and has more tooling support outside java ecosystem. My conclusion: properties files work and are quite nice to handle but limited to java. Po files are a common standard and more powerfull. Because we already have some indirection built in we can use whatever file format we want :)
https://github.com/awkay/easy-i18n looks also nice 

*  cosmetic notes
all valid and I will adress them today.

* bug 
Sorry for that workaround with restarting the whole application. I would prefer getting rid of all the static translations. That would make the initialization much nicer and would allow for dynamic translation changes. I think it would be a worth the effort.

**Comment by liushuyu** [comment]
>So now I'm in a bit of a dilemma. If the various tools of the internet want .po files and @liushuyu's initial instinct was to use .po files, perhaps we just bundle a few ANT utilities and embrace the format.

So initially I was afraid that there'll be some complex language features that'll be used (plural forms, currency, date format, etc) and when I finished the translation I found (IIRC) there was none. If there was, it'd be better to use gettext since it's almost a standard for dealing with locales. If there was one and you want less dependencies, well, native Java property system will be sufficient I think.

**Comment by tresf** [comment]
>  Java property system will be sufficient I think.

Ok, how best to chain to ANT?  Does ANT's JavaScript engine have full file/io that we can use?  Or is there a pre-compiled JAR?  I'm not attached to use of the word `gettext` so generically.  Thoughts are welcome here, but what I'd like to avoid is building a temporary `.class` objects just for use inside ANT.

**Comment by liushuyu** [comment]
>Ok, how best to chain to ANT? Does ANT's JavaScript engine have full file/io that we can use? Or is there a pre-compiled JAR? I'm not attached to use of the word gettext so generically. Thoughts are welcome here, but what I'd like to avoid is building a temporary .class objects just for use inside ANT.

According to their documentation, they have a Java-like filesystem API exposed to Javascript. And anything else is based on Rhino which I think compliant with ECMAScript version 1.7

**Comment by liushuyu** [comment]
>hm I don't understand what you mean with ANT and javascript?
My understanding is that ant is a build tool which executes Tasks written in Java through some xml configuration.

@tresf Mean there's a Javascript engine in ANT that can also execute tasks retrieve/modify project properties etc without compiling the bytecode.

>I mean the current solution is not much overhead. We can even make it an optional build step which is manually triggered when translations are updated

Actually, if that's the case, we can also use Travis CI to process the translations.

**Comment by johann-sonntagbauer** [comment]
The full build takes 14-20sec on my machine. The Task compilation and Text extraction takes 1-2 sec. So no big deal.

**Comment by liushuyu** [comment]
@johann-sonntagbauer I can see there's merge conflict in this PR, so would you mind resolving the conflict? Since `2.1` was rebased some time ago, so I recommend to rebase or apply the changes yourself after resetting your branch.

**Comment by johann-sonntagbauer** [comment]
@liushuyu ha I am lazy but not that lazy :D

**Comment by johann-sonntagbauer** [comment]
I don't understand why the travis builds are broken. Is there any problem with the changes?

**Comment by johann-sonntagbauer** [comment]
@tresf the dropdown locale selection is not that nice
image

image

**Comment by tresf** [comment]
> @tresf the dropdown locale selection is not that nice

Both solutions look great.  The menu simplifies the code, so that's fine.

> I don't understand why the travis builds are broken. Is there any problem with the changes?

I'm guessing the script is mucking up the `nsis` script on Windows.

**Comment by johann-sonntagbauer** [comment]
@tresf so menu it is :)

I try to find out whats wrong - on my machine it compiles correctly :(

**Comment by tresf** [comment]
> I try to find out whats wrong - on my machine it compiles correctly :(

I'll check it out.  I have an identical Ubuntu machine to Travis-CI to try on.

**Comment by tresf** [comment]
> I don't understand why the travis builds are broken. 

@johann-sonntagbauer I can't reproduce the error off of your branch either -- might have something to do with the merge.  I've never seen Travis do this before.  Can you rebase your branch and see what happens?

**Comment by liushuyu** [comment]
>@johann-sonntagbauer I can't reproduce the error off of your branch either -- might have something to do with the merge. I've never seen Travis do this before. Can you rebase your branch and see what happens?

Well, sometimes I observe random problems with `nsis` builder even with my PR before. And I tried to switch to container based infrastructure, it became more often (these commits are not pushed)

**Comment by tresf** [comment]
@liushuyu please pull your changes out of 2.1 and put them here.  I'm not sure if this was done on accident or if there was a misunderstanding, but this feature is not ready for 2.1 and should live inside a PR only.

https://github.com/qzind/tray/commits/2.1

**Comment by liushuyu** [comment]
>@liushuyu please pull your changes out of 2.1 and put them here. I'm not sure if this was done on accident or if there was a misunderstanding, but this feature is not ready for 2.1 and should live inside a PR only.

I am very sorry, I thought you meant I push my changes to `2.1` branch so he can target the PR directly to `2.1`.

**Comment by tresf** [comment]
> I am very sorry, I thought you meant I push my changes to 2.1 branch so he can target the PR directly to 2.1.

Not a problem at all, I don't mind you rolling the state of the branch back.  @johann-sonntagbauer will just have to do a hard reset once everything's rebased, you should have full push access to his `i18nsupport` branch if he's OK with it. :)

**Comment by johann-sonntagbauer** [comment]
no problem simply tell when to rebase again. 
My changes are all based on the current 2.1 branch.

**Comment by tresf** [comment]
> I don't understand why the travis builds are broken.

Just did a [test merge onto a temporary branch](https://github.com/tresf/tray/pull/2) and it builds 100% fine with `nsis`, so this is quite bazaar.

> Well, sometimes I observe random problems with nsis builder even with my PR before. 

Yes, I've noticed it has a tendency to break sometimes when the slashes are forward `/` and not backslashes but it's completely random.  It's been a while since I've run into this.  I guess we'll trust our local over Travis-CI for the time being.  We haven't had a failed Travis-CI build in a very long time so I assumed this was due to the search/replace getting out of hand, but I have no evidence of this locally and the code calls `"glob:**.java"`. :/

**Comment by liushuyu** [comment]
>no problem simply tell when to rebase again.
My changes are all based on the current 2.1 branch.

You don't need to rebase again, since your branch already have my changes. This reset only affects main repository.

**Comment by tresf** [comment]
> no problem simply tell when to rebase again.

@liushuyu already did it.  He's a ninja.

**Comment by tresf** [comment]
So I can confirm the build errors... 

This is what the MacOS packager is saying.  I'll investigate what might be causing this.

```
get-version:
     [echo] Version [WARN] 2018-04-09 19:28:54,402 @ qz.common.TrayManager:?
     [echo] 	Could not load file: /Users/travis/Library/Application Support/qz/prefs.properties, reason: /Users/travis/Library/Application Support/qz/prefs.properties (No such file or directory)
     [echo] 2.1.0-RC4
     [echo] Size: 15390 KB
```

**Comment by liushuyu** [comment]
>Yes, I've noticed it has a tendency to break sometimes when the slashes are forward / and not backslashes but it's completely random. It's been a while since I've run into this. I guess we'll trust our local over Travis-CI for the time being. We haven't had a failed Travis-CI build in a very long time so I assumed this was due to the search/replace getting out of hand, but I have no evidence of this locally and the code calls "glob:**.java". :/

I made Travis CI print out everything and I think I found the problem:
```nsis
!include MUI2.nsh
!include x64.nsh
!include LogicLib.nsh

!ifdef NSIS_UNICODE
	!addplugindir "/home/travis/build/liushuyu/tray/ant/windows/nsis/Plugins/Release_Unicode"
!else
	!addplugindir "/home/travis/build/liushuyu/tray/ant/windows/nsis/Plugins/Release_ANSI"
!endif

!addincludedir "/home/travis/build/liushuyu/tray/ant/windows/nsis/Include/"
!include StdUtils.nsh

Name "QZ Tray"
OutFile "/home/travis/build/liushuyu/tray/out\qz-tray-Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
2.1.0-RC4.exe"
RequestExecutionLevel admin

;-------------------------------
```

>OutFile "/home/travis/build/liushuyu/tray/out\qz-tray-Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
2.1.0-RC4.exe"

See? Some random Java option strings (should be print to stderr however, not should why it's here)

**Comment by johann-sonntagbauer** [comment]
yes thats the problem I will fix it

**Comment by tresf** [comment]
It's because there's a static constructor for the `prefs`.

To reproduce:

```
rm -rf ~/.qz/
java -jar out/dist/qz-tray.jar --version
```

It should never init the `prefs` object.

**Comment by liushuyu** [comment]
>yes thats the problem I will fix it

I have already worked out a fix, can I push to your branch now?

**Comment by johann-sonntagbauer** [comment]
the log output is the problem, because it will be interpreted as version number :) with new lines which will break the scripts.

@prefs yes I know, but to proper initialize the static constants I had to implement the static initializer. I will put a check around that.

@liushuyu I have invited you, hope that is enough :)

**Comment by tresf** [comment]
> @liushuyu I have invited you, hope that is enough :)

He has push access to `qzind/tray`, which grants him push access to this PR's branch automagically. :)

**Comment by johann-sonntagbauer** [comment]
lots to learn for me :)

**Comment by johann-sonntagbauer** [comment]
@tresf yes I will remove the statics - takes some time

**Comment by tresf** [comment]
Please don't hack the build system to fix a coding mistake.  This affects more than just Travis-CI.  The [test-case](https://github.com/qzind/tray/pull/303#issuecomment-379879091) I've provided causes the exact same build problem, fixing it in Travis does nothing.

If we eventually need the `.properties` to be loaded (such as future translating e.g. `--help`) we can suppress that message but for now I think it can be lazy init.

**Comment by liushuyu** [comment]
```nsis
Name "QZ Tray"
OutFile "/home/travis/build/liushuyu/tray/out\qz-tray-[WARN] 2018-04-09 20:30:16,426 @ qz.common.TrayManager:?
	Could not load file: /home/travis/.qz/prefs.properties, reason: /home/travis/.qz/prefs.properties (No such file or directory)
2.1.0-RC4.exe"
```

I see, it's coding issue.

>Please don't hack the build system to fix a coding mistake. This affects more than just Travis-CI. The test-case I've provided causes the exact same build problem, fixing it in Travis does nothing.

This didn't fix the problem stated above, but random `nsis` problem caused by `Picked up _JAVA_OPTIONS` thing.

**Comment by liushuyu** [comment]
Still not working:

```
[exec] pkgbuild: error: directory "/Users/travis/build/qzind/tray/out/qz-tray-[WARN] 2018-04-09 20:41:12,485 @ qz.common.TrayManager:?
     [exec] 	Could not load file: /Users/travis/Library/Application Support/qz/prefs.properties, reason: /Users/travis/Library/Application Support/qz" does not exist for writing "prefs.properties (No such file or directory)
```

**Comment by johann-sonntagbauer** [comment]
I know - I have to lazy init all static gettext calls - as I said it takes a while :)

**Comment by liushuyu** [comment]
>I know - I have to lazy init all static gettext calls - as I said it takes a while :)

Sorry if I bothered you and take your time :+1:

**Comment by johann-sonntagbauer** [comment]
sorry for the stupid mistake - I try to come up with a nice solution for the constant labels. Current solution is very fragile.

**Comment by tresf** [comment]
> I know - I have to lazy init all static gettext calls - as I said it takes a while :)

Shouldn't have to change that much.  I'd happily take a look.

**Comment by tresf** [comment]
@johann-sonntagbauer I don't want you to write half of @liushuyu's work because of this.  If it's ok, let me revert the last two commits and create a lazy init.

**Comment by tresf** [comment]
Something like this... 

```diff
diff --git a/src/qz/common/I18NLoader.java b/src/qz/common/I18NLoader.java
index ce3c263..2b7d210 100644
--- a/src/qz/common/I18NLoader.java
+++ b/src/qz/common/I18NLoader.java
@@ -15,9 +15,6 @@ public class I18NLoader {
 
     private static final Logger log = LoggerFactory.getLogger(I18NLoader.class);
 
-    private static ResourceBundle msg;
-    private static PropertyHelper prefs;
-
     public static final List<Locale> SUPPORTED_LOCALES = Collections.unmodifiableList(Arrays.asList(
             Locale.forLanguageTag("de"),
             Locale.forLanguageTag("en"),
@@ -26,6 +23,12 @@ public class I18NLoader {
             Locale.forLanguageTag("zh-TW")
     ));
 
+
+    private static I18NLoader instance;
+
+    private ResourceBundle msg;
+    private PropertyHelper prefs;
+
     /**
      * Get localized strings
      *
@@ -35,7 +38,7 @@ public class I18NLoader {
 
     public static String gettext(String id) {
         try {
-            return msg.getString(id);
+            return instance.msg.getString(id);
         }
         catch(MissingResourceException e) {
             // fail-safe action, we'll just return original string
@@ -44,8 +47,15 @@ public class I18NLoader {
         }
     }
 
+    public static I18NLoader getInstance() {
+        if (instance == null) {
+            instance = new I18NLoader();
+        }
+        return instance;
+    }
+
     public static Locale getCurrentLocale() {
-        return Locale.forLanguageTag(prefs.getProperty(I18N_LOCALE_PROPERTY, DEFAULT_LOCALE));
+        return Locale.forLanguageTag(getInstance().prefs.getProperty(I18N_LOCALE_PROPERTY, DEFAULT_LOCALE));
     }
 
     /**
@@ -54,8 +64,8 @@ public class I18NLoader {
      * @param locale Locale to change to
      */
     public static void changeLocale(Locale locale) {
-        prefs.setProperty(I18N_LOCALE_PROPERTY, locale.toLanguageTag());
-        prefs.save();
+        getInstance().prefs.setProperty(I18N_LOCALE_PROPERTY, locale.toLanguageTag());
+        getInstance().prefs.save();
 
         restartApplication(() -> log.info("restart because of locale change"));
     }
@@ -66,8 +76,8 @@ public class I18NLoader {
      * @param propertyHelper PropertyHelper
      */
     public static void setup(PropertyHelper propertyHelper) {
-        prefs = propertyHelper;
-        msg = Utf8ResourceBundle.getBundle(I18N_LOCATION, getCurrentLocale());
+        getInstance().prefs = propertyHelper;
+        getInstance().msg = Utf8ResourceBundle.getBundle(I18N_LOCATION, getCurrentLocale());
     }
 }
```

**Comment by tresf** [comment]
After seeing the headache that un-static'n the Constants caused I decided to simply suppress this warning.  Sorry about the runaround.

**Comment by liushuyu** [comment]
Okay, so do we need to clean up the PR commits here? There are several revert commits, and I guess since this is in a PR, rebasing won't do much harm.

**Comment by tresf** [comment]
They'll get squashed out when merged they're fine.

**Comment by liushuyu** [comment]
>They'll get squashed out when merged they're fine.

I see, thanks

**Comment by johann-sonntagbauer** [comment]
@tresf and @liushuyu  thanks for caring so much. It is a great experience for me to work with you on that feature. 
So the thinks to improve are:
* Restart on MAC
* extract gettext task compilation in ant script

**Comment by tresf** [comment]
@johann-sonntagbauer thanks for the code.  It's taking us here a while to get to this, but it's on the list.  Thanks!

**Comment by johann-sonntagbauer** [comment]
@tresf no problem, take your time. If you want something to be improved further let me know.

**Comment by tresf** [comment]
In preparation of the 2.1 release, I've squashed the commits from this PR into a single commit on my own fork just incase the fast forward from 2.0 causes issues. https://github.com/qzind/tray/compare/2.1...tresf:i18n

**Comment by tresf** [comment]
We're resurrecting this PR over at #469.
* Switched to JSON file format
* Rebased against the 2.1 branch to fix the above conflicts.

@johann-sonntagbauer and @liushuyu sorry for the delay.  We'd like to see this feature live with the upcoming 2.1 release.  Any help is greatly appreciated.

**Comment by tresf** [comment]
Closing as this has been superseded by #469.

**Pull request closed without merging**
