### PR TITLE
Replaced deprecated URLWhitelist

### LINKED ISSUE #1277: Chrome: qz:launch shows pop-up
At some point, our code to suppress the `qz:launch` pop-ups stopped working.

Initial glance would blame the deprecation of `URLWhitelist`, but changing this to `URLAllowlist` doesn't seem to fix the symptom.
* ⚠️ https://chromeenterprise.google/policies/#URLWhitelist
* ✅ https://chromeenterprise.google/policies/#URLAllowlist

With regards to whether or not the "Always allow" checkbox is shown, there's a policy for that as well, which we don't currently configure:
* https://chromeenterprise.google/policies/#ExternalProtocolDialogShowAlwaysOpenCheckbox

image

### PR DESCRIPTION
**Pull request by Vzor-**
Partially addresses/related to #1277

### CODE REVIEW

**Comment by tresf** [comment]
> Fixes #1277

What about Windows, Linux?

**Comment by tresf** [comment]
I tested this on Windows 11 ARM64 and the popup still shows.

image

**Review by tresf — CHANGES_REQUESTED** [review]
Changes are needed; seems to still be broken on Windows.

**Comment by Vzor-** [comment]
This is a **working** policy on MacOS
Screenshot 2024-08-29 at 2 04 01 PM
this is a **not working** policy on Windows. 
Screenshot 2024-08-29 at 2 03 14 PM
They seem similar, but there are some minor discrepancies. I'll try resolving these to find the issue.

**Comment by tresf** [comment]
@Vzor- based on our conversations, I believe you found an upstream bug here but this bug report was never updated to reflect it.  Furthemore, I do not believe that an upstream bug report was ever filed to accompany this downstream bug.  Can you please provide your findings so that we can take action on this?

**Comment by Vzor-** [comment]
Certainly. I was in the middle of testing a possible solution when I had to jump to a more pressing issue. This will be the next issue I start.

**Comment by tresf** [comment]
> Certainly. I was in the middle of testing a possible solution when I had to jump to a more pressing issue. This will be the next issue I start.

It's been a month and the upstream bug/upstream bug report still isn't mentioned here or in #1277.  For sake of completeness, I'm going to change the wording of this PR from "fixes" to "related", merge and paste your screenshot over there.  Please provide the details that you gathered researching this problem to #1277 so that we can determine next actions.

**Review by tresf — APPROVED** [review]

**Pull request merged**
