### PR TITLE
Apple installer detects arch

### LINKED ISSUE #875: Warn when running on wrong architecture
The QZ Tray installer should warn when you're running it on the wrong architecture, so something like https://github.com/qzind/tray/issues/873 does not happen.

### PR DESCRIPTION
**Pull request by Vzor-**
Does what it says on the tin

**Edit:** Closes #875

### CODE REVIEW

**Comment by tresf** [comment]
@Vzor- we're getting some users also complaining that 32-bit Windows doesn't offer an intuitive message (we don't prepare installers for this either).

**Comment by Vzor-** [comment]
image
Yea, that's not great.

**Comment by tresf** [comment]
> Yea, that's not great.

I've moved this to https://github.com/qzind/tray/issues/1027.

**Comment by tresf** [comment]
The additional arch info in the installer knows to install Rosetta now.  That's cool.

image

**Pull request merged**
