### PR TITLE
Add TypeScript File for Improved Type Safety

### PR DESCRIPTION
**Pull request by tomashlavac**
This pull request introduces a new TypeScript file to enhance the type safety of this project. TypeScript offers static typing, enabling early detection of potential bugs and improved developer productivity. The new file includes type definitions for all functions, ensuring better code maintainability and readability.

All types are based on documentation from [qz.io/api/](https://qz.io/api/) and manually rewritten to TS.
Feel free to code review and leave comments.

Cheers

### CODE REVIEW

**Comment by tresf** [comment]
Thanks!  We've been asked for this is the past, but we have no interest in maintaining such a file.  For that reason we've chosen to mark such requests as `wontfix`.  At one point we attempted to automatically convert the JSDoc to a typescript definition file and were unsuccessful in doing so.  We may change our stance on this in the future if we can find a way to automa

**Comment by tresf** [comment]
Sorry, I did not mean to close this prior to conversation. 😅

**Comment by tomashlavac** [comment]
Hi @tresf ,

thank you for your prompt response. I genuinely appreciate your concern regarding this matter.

Given the circumstances, I will take the necessary steps to address the issue by contributing the TypeScript file to the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repository.

**Comment by tresf** [comment]
> Hi @tresf ,
> 
> thank you for your prompt response. I genuinely appreciate your concern regarding this matter.
> 
> Given the circumstances, I will take the necessary steps to address the issue by contributing the TypeScript file to the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repository.

Thank you.  I will leave this open until the PR has been merged there.

**Comment by tomashlavac** [comment]
I have created [pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68745) in DefinitelyTyped repository

**Comment by tresf** [comment]
Closing in favor of the `DefinitelyTyped` project contribution (thanks!)

**Pull request closed without merging**
